
@startuml
rectangle "Admin" as admin
rectangle "Zewnętrzny System Zleceń" as zsz
rectangle Aplikacja as app {
	rectangle "System Zleceń" as sz{
		(Przypisanie Notatki) as assign
    }
    (System Notatek) as sz
    (System Użytkowników) as su:


}
@enduml
