
@startuml
rectangle "Admin" as admin
rectangle "Zewnętrzny System Zleceń" as zsz
rectangle Aplikacja as app {
	rectangle "System Zleceń" as sz{
		(Przypisanie Notatki) as assign_n
		(Przypisanie Użytkownika) as assign_u
    }
    (System Notatek) as sn
	
	zsz --> assign_n
	zsz --> assign_u
	admin --> assign_n
	admin --> assign_u
}
@enduml
