
@startuml
    rectangle "Administrator" as admin
    rectangle "System Użytkowników" as sn{
	(Dodanie użytkownika) as add
	(Usunięcie użytkownika) as del
	(Edycja użytkownika) as edit
	(Przeglądanie użytkowników) as view
	(Ustawienie uprawnień) as perm
	(Tworzenie zespołu) as teamadd
	(Usuwanie zespołu) as teamdel
	(Edycja zespołu) as teamedit
	(Przeglądanie zespołów) as teamview
    }
    (System Zleceń) as sz
    (System Notatek) as su
    database "Użytkownicy" as dbu
    database "Zespoły" as dbz

    admin --> add
    admin --> del
    admin --> edit
    admin <-- view
    admin --> perm
    admin --> teamadd
    admin --> teamdel
    admin --> teamedit
    admin <-- teamview

    add --> dbu: użytkownik
    del --> dbu: użytkownik
    edit --> dbu: użytkownik
    view <-- dbu: użytkownik

    perm --> dbu: uprawnienia
    perm --> dbz: uprawnienia

    teamadd --> dbz: zespół
    teamdel --> dbz: zespół
    teamedit --> dbz: zespół
    teamview <-- dbz: zespół
@enduml
