# This is a GitHub Workflow configuration
# Sytnax reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  push:
    paths:
      - '*.puml'

name: PlantUML
jobs:
  generate_images:
    name: Update images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate images from diagrams
        uses: docker://miy4/plantuml
        with:
          args: "*.puml "
      - name: Commit updated diagram images
        uses: EndBug/add-and-commit@v2.1.0
        with:
          message: Update PlantUML diagram images
          path: "."
          pattern: "*.png"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
