# This is a GitHub Workflow configuration
# Sytnax reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Plant UML Diagram Generator

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate and commit diagrams
        uses: abekoh/commit-plantuml-action@1.0.3
        with:
          botEmail: ${{ secrets.BOT_EMAIL }}
          botGithubToken: ${{ secrets.token }}
          enableReviewComment: true
